// shared/constants/reservations.js - Constantes des réservations

// === STATUTS DES RÉSERVATIONS ===
export const RESERVATION_STATUS = {
  PENDING: 'pending',
  CONFIRMED: 'confirmed',
  SEATED: 'seated',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled',
  NO_SHOW: 'no_show'
};

export const RESERVATION_STATUS_LIST = Object.values(RESERVATION_STATUS);

// === TRANSITIONS AUTORISÉES ===
export const RESERVATION_STATUS_TRANSITIONS = {
  [RESERVATION_STATUS.PENDING]: [
    RESERVATION_STATUS.CONFIRMED,
    RESERVATION_STATUS.CANCELLED
  ],
  [RESERVATION_STATUS.CONFIRMED]: [
    RESERVATION_STATUS.SEATED,
    RESERVATION_STATUS.CANCELLED,
    RESERVATION_STATUS.NO_SHOW
  ],
  [RESERVATION_STATUS.SEATED]: [
    RESERVATION_STATUS.COMPLETED
  ],
  [RESERVATION_STATUS.COMPLETED]: [],
  [RESERVATION_STATUS.CANCELLED]: [],
  [RESERVATION_STATUS.NO_SHOW]: []
};

// === LABELS DES STATUTS ===
export const RESERVATION_STATUS_LABELS = {
  [RESERVATION_STATUS.PENDING]: 'En attente',
  [RESERVATION_STATUS.CONFIRMED]: 'Confirmée',
  [RESERVATION_STATUS.SEATED]: 'Installée',
  [RESERVATION_STATUS.COMPLETED]: 'Terminée',
  [RESERVATION_STATUS.CANCELLED]: 'Annulée',
  [RESERVATION_STATUS.NO_SHOW]: 'No-show'
};

// === COULEURS DES STATUTS ===
export const RESERVATION_STATUS_COLORS = {
  [RESERVATION_STATUS.PENDING]: 'warning',
  [RESERVATION_STATUS.CONFIRMED]: 'success',
  [RESERVATION_STATUS.SEATED]: 'info',
  [RESERVATION_STATUS.COMPLETED]: 'primary',
  [RESERVATION_STATUS.CANCELLED]: 'danger',
  [RESERVATION_STATUS.NO_SHOW]: 'dark'
};

// === SOURCES DE RÉSERVATION ===
export const RESERVATION_SOURCES = {
  PHONE: 'phone',
  ONLINE: 'online',
  WALK_IN: 'walk_in',
  ADMIN: 'admin'
};

export const RESERVATION_SOURCES_LIST = Object.values(RESERVATION_SOURCES);

// === DURÉES PAR DÉFAUT (en minutes) ===
export const DEFAULT_RESERVATION_DURATION = {
  LUNCH: 90,
  DINNER: 120,
  BRUNCH: 120,
  EVENT: 180
};

// === CRÉNEAUX HORAIRES ===
export const TIME_SLOTS = {
  LUNCH_START: '12:00',
  LUNCH_END: '14:30',
  DINNER_START: '19:00',
  DINNER_END: '22:00'
};

// === VALIDATION ===
export const RESERVATION_VALIDATION = {
  MIN_GUESTS: 1,
  MAX_GUESTS: 12,
  MIN_ADVANCE_HOURS: 1,
  MAX_ADVANCE_DAYS: 30
};